title: "&8Custom Smithing Table"
itemsadder-furniture: "myitems:smithing_table" #Also rename default.yml to [custom_smithing_table] for it to work!
structure:
  - "X X X X X X X X X"
  - "X T B A X R X X X"
  - "X X X X X X X X Z"

# T - template
# B - base
# A - addition
# R - result
# X - filler
# Z - back button for recipe book

filler:
  material: BLACK_STAINED_GLASS_PANE
  name: ""

effects:
  on-craft:
    sound:
      sound: BLOCK_ANVIL_USE
      volume: 1.0
      pitch: 1.0
    particle:
      particle: CRIT
      count: 10
      offset-x: 0.5
      offset-y: 0.5
      offset-z: 0.5

recipes:
  first_recipe:
    result:
      material: NETHERITE_CHESTPLATE
      amount: 1
    template:
      material: NETHERITE_UPGRADE_SMITHING_TEMPLATE
      amount: 1
    base:
      material: DIAMOND_CHESTPLATE
      amount: 1
    addition:
      material: NETHERITE_INGOT
      amount: 1