title: "&dКастомный верстак"
itemsadder-furniture: "myitems:custom_workbench" #Also rename default.yml to [custom_workbench] for it to work!
structure:
  - "O X X X O X X X X"
  - "X X O X X X X X X"
  - "X O O O X X X R X"
  - "X X O X X X X X X"
  - "O X X X O X X X X"

filler:
  material: BLACK_STAINED_GLASS_PANE
  name: ""
  lore: []

effects:
  on-craft:
    sound:
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      category: PLAYERS
      volume: 1.0
      pitch: 1.2
    particle:
      particle: ENCHANTMENT_TABLE
      count: 30
      offset-x: 0.5
      offset-y: 1.0
      offset-z: 0.5
      speed: 0.5

recipes:
  first:
    result:
      material: IRON_BLOCK
      amount: 1
    0:
      material: STONE
      amount: 1
    1:
      material: STONE
      amount: 1
    2:
      material: STONE
      amount: 1
    3:
      material: STONE
      amount: 1
    4:
      material: STONE
      amount: 1
    5:
      material: STONE
      amount: 1
    6:
      material: STONE
      amount: 1
    7:
      material: STONE
      amount: 1
    8:
      material: STONE
      amount: 1
  
  second:
    result:
      material: DIAMOND_BLOCK
      amount: 1
    0:
      material: DIAMOND
      amount: 1
    1:
      material: DIAMOND
      amount: 1
    2:
      material: DIAMOND
      amount: 1
    3:
      material: DIAMOND
      amount: 1
    4:
      material: EMERALD
      amount: 1
    5:
      material: DIAMOND
      amount: 1
    6:
      material: DIAMOND
      amount: 1
    7:
      material: DIAMOND
      amount: 1
    8:
      material: DIAMOND
      amount: 1
