title: "&dCustom furnace"
itemsadder-furniture: "myitems:custom_furnace" #Also rename default.yml to [custom_furnace] for it to work!
structure:
  - "X X X X X X X X X"
  - "X X X X X X X X X"
  - "X A B X P X R X X"
  - "X X U X X X X X X"
  - "X X X X X X X X X"

filler:
  material: BLACK_STAINED_GLASS_PANE
  name: ""
  lore: []

progress-bar:
  stages: 10  #There are 3 custom stages: 5, 10 and 20. You can delete everything in progress-bar and leave only stages: 5 because plugin has automatic preset for 5 stages, if you want 10 or 20 stages, then you will have to set up them yourself.
  0:
    material: RED_CONCRETE
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  1:
    material: RED_TERRACOTTA
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  2:
    material: ORANGE_TERRACOTTA
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  3:
    material: YELLOW_TERRACOTTA
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  4:
    material: YELLOW_CONCRETE
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  5:
    material: LIME_TERRACOTTA
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  6:
    material: LIME_CONCRETE
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  7:
    material: EMERALD_BLOCK
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  8:
    material: GREEN_TERRACOTTA
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"
  9:
    material: GREEN_CONCRETE
    name: "&cProgress: %progress%"
    lore:
      - "&7%ticks% / %total_ticks% ticks"
      - "&7%seconds_left% seconds left"

effects:
  cooking-interval: 20
  on-start:
    sound:
      sound: BLOCK_FURNACE_FIRE_CRACKLE
      category: BLOCKS
      volume: 1.0
      pitch: 1.0
    particle:
      particle: FLAME
      count: 15
      offset-x: 0.3
      offset-y: 0.3
      offset-z: 0.3
      speed: 0.05
  on-cooking:
    sound:
      sound: BLOCK_LAVA_POP
      category: BLOCKS
      volume: 0.5
      pitch: 1.5
    particle:
      particle: SMOKE_NORMAL
      count: 5
      offset-x: 0.2
      offset-y: 0.4
      offset-z: 0.2
      speed: 0.02
  on-complete:
    sound:
      sound: BLOCK_ANVIL_LAND
      category: BLOCKS
      volume: 0.8
      pitch: 1.8
    particle:
      particle: VILLAGER_HAPPY
      count: 20
      offset-x: 0.5
      offset-y: 0.5
      offset-z: 0.5
      speed: 0.1

recipes:
  1z:
    cook-time: 100
    result:
      material: IRON_BLOCK
      amount: 1
    raws:
      A: [IRON_ORE]
      B: [DEEPSLATE]
    fuels:
      U: [COAL]

# All placeholders for progress-bar: %progress%, %ticks%, %total_ticks%, %seconds_left%